spring.application.name=backend

# * Database Config
spring.config.import=classpath:database.properties, classpath:jwt.properties

# * Spring Config
spring.main.banner-mode=off
logging.level.root=warn
server.port=8080