"""Shared message type used across all layers."""

from typing import Literal, TypedDict


class Message(TypedDict):
    """
    A single chat message exchanged between a role and the model.

    Attributes:
        role: Who sent the message.
               - "system"    : The persona/instruction given to the model at the start.
               - "user"      : Input from the human.
               - "assistant" : Reply generated by the model.
        content: The text body of the message.
    """

    role: Literal["system", "user", "assistant"]
    content: str
